"""Reduced-order modelling utilities."""

from .datasets import ROMDataset, load_rom_dataset, load_project2_dataset_by_name
from .pod import (
    PODResult,
    as_snapshot_matrix,
    compute_pod,
    cumulative_energy_from_singular_values,
    project_snapshots,
    reconstruct_snapshots,
    relative_frobenius_error,
    select_rank,
)
from .preprocessing import (
    PODPreprocessingResult,
    ParameterScaler,
    build_pod_preprocessing,
    fit_parameter_scaler,
    save_pod_preprocessing,
)
from .splits import TrainTestSplit, make_train_test_split
from .suites import (
    ROMMethodSpec,
    ALL_METHODS,
    COMMON_METHODS,
    INTRUSIVE_METHODS,
    NONINTRUSIVE_METHODS,
    get_method_spec,
    method_names_for_suite,
    methods_for_suite,
    validate_method_list,
)
from .intrusive import (
    LoadedPOD,
    PODGalerkinCapability,
    PODProjectedMetrics,
    evaluate_pod_projection,
    load_pod_artifact,
    write_intrusive_projection_summary,
)
from .nonintrusive import (
    CoefficientRegressor,
    NonIntrusiveMetrics,
    LEGACY_PODI_CONFIG,
    LEGACY_PODGPR_CONFIG,
    LEGACY_PODNN_CONFIG,
    LEGACY_PODAE_CONFIG,
    LegacyPODIRegressor,
    LegacyGPRRegressor,
    LegacyTorchNNRegressor,
    LegacyPODAERegressor,
    make_coefficient_regressor,
    evaluate_coefficient_regressor,
    write_nonintrusive_result,
)

__all__ = [
    "ROMDataset",
    "load_rom_dataset",
    "load_project2_dataset_by_name",
    "PODResult",
    "as_snapshot_matrix",
    "compute_pod",
    "cumulative_energy_from_singular_values",
    "project_snapshots",
    "reconstruct_snapshots",
    "relative_frobenius_error",
    "select_rank",
    "PODPreprocessingResult",
    "ParameterScaler",
    "build_pod_preprocessing",
    "fit_parameter_scaler",
    "save_pod_preprocessing",
    "TrainTestSplit",
    "make_train_test_split",
    "ROMMethodSpec",
    "ALL_METHODS",
    "COMMON_METHODS",
    "INTRUSIVE_METHODS",
    "NONINTRUSIVE_METHODS",
    "get_method_spec",
    "method_names_for_suite",
    "methods_for_suite",
    "validate_method_list",
    "LoadedPOD",
    "PODGalerkinCapability",
    "PODProjectedMetrics",
    "evaluate_pod_projection",
    "load_pod_artifact",
    "write_intrusive_projection_summary",
    "CoefficientRegressor",
    "NonIntrusiveMetrics",
    "LEGACY_PODI_CONFIG",
    "LEGACY_PODGPR_CONFIG",
    "LEGACY_PODNN_CONFIG",
    "LEGACY_PODAE_CONFIG",
    "LegacyPODIRegressor",
    "LegacyGPRRegressor",
    "LegacyTorchNNRegressor",
    "LegacyPODAERegressor",
    "make_coefficient_regressor",
    "evaluate_coefficient_regressor",
    "write_nonintrusive_result",
]
